### ISSUE TITLE
Ошибка при выполнении npm run build

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-front#2]
npm run build
> clean-webpack-plugin: C:\Golden\NS\gdmn-front\dist has been removed.
>  92% chunk asset optimization UglifyJSPlugin
> <--- Last few GCs --->
> 
> [8544:000001C2DFDBC420]    53422 ms: Mark-sweep 1352.2 (1439.6) -> 1338.2 (1440.1) MB, 961.8 / 0.0 ms  (average mu = 0.133, current mu = 0.034) allocation failure scavenge might not succeed
> [8544:000001C2DFDBC420]    54431 ms: Mark-sweep 1353.3 (1440.1) -> 1339.4 (1441.1) MB, 979.0 / 0.0 ms  (average mu = 0.084, current mu = 0.030) allocation failure scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 0000015E1E1841C1]
>     1: StubFrame [pc: 0000015E1E1CE33F]
> Security context: 0000015B8CE9E589 <JSObject>
>     2: replace [0000015B8CE90BD1](this=00000053B50C5AD9 <String[4]: mar.>,0000029BAC63F851 <JSRegExp <String[44]: [\\\b\f\n\r\v\t\x22\x27\u2028\u2029\0\ufeff]>>,0000029BAC63F889 <JSFunction (sfi = 00000381F7C7FA79)>)
>     3: make_string(aka make_string) [000002A78E3B3FC9] [00000124E01022E1 <undefined>:~5643] [pc=000...
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: node::DecodeWrite
>  2: node_module_register
>  3: v8::internal::FatalProcessOutOfMemory
>  4: v8::internal::FatalProcessOutOfMemory
>  5: v8::internal::Heap::MaxHeapGrowingFactor
>  6: v8::internal::ScavengeJob::operator=
>  7: v8::internal::ScavengeJob::operator=
>  8: v8::internal::Heap::MaxHeapGrowingFactor
>  9: v8::internal::Factory::NewFillerObject
> 10: v8::internal::ParseInfo::GetFlag
> 11: 0000015E1E1841C1

**Comment by cognitivim** [comment]
точно на последнем коммите? я пофиксила в 67a8dc76bf7ad2ac516fb221a1c65493446c5b81

**Comment by gsbelarus** [comment]
ок. попробую объединить изменения.
